import { Question } from '@/types/adapts';

const ParentQuestions: Question[] = [
    { id: 1,  question: "My child feels sad.", factor: "MDD" },
    { id: 2,  question: "My child feels afraid of being alone at home.", factor: "SeA" },
    { id: 3,  question: "My child worries about stuff.", factor: "GAD" },
    { id: 4,  question: "My child worries when I'm away from him/her.", factor: "SeA" },
    { id: 5,  question: "My child has problems sleeping.", factor: "MDD" },
    { id: 6,  question: "My child has no energy to do things.", factor: "MDD" },
    { id: 7,  question: "My child feels afraid for no reason.", factor: "PD"},
    { id: 8,  question: "When my child has a problem, his/her stomach gets upset.", factor: "PD"},
    { id: 9,  question: "My child worries about making mistakes.", factor: "SoA"},
    { id: 10, question: "My child gets very tired.", factor: "MDD"},
    { id: 11, question: "My child doesn't have much fun anymore.",  factor: "MDD"},
    { id: 12, question: "My child has problems concentrating.", factor: "MDD"},
    { id: 13, question: "My child gets scared when he/she has to take a test.", factor: "SoA"},
    { id: 14, question: "My child is bothered by thoughts of dying.", factor: "GAD"},
    { id: 15, question: "My child worries that something bad will happen.", factor: "GAD"},
    { id: 16, question: "My child worries about getting bad grades.", factor: "SoA"},
    { id: 17, question: "It bothers my child when someone is angry with him/her.", factor: "SoA"},
    { id: 18, question: "My child doesn't feel like doing anything.", factor: "MDD"},
    { id: 19, question: "My child worries that something bad will happen to me or people he/she loves.", factor: "GAD"},
    { id: 20, question: "My child is scared of sleeping alone.", factor: "SeA"},
    { id: 21, question: "My child worries about embarrassing him/her self.", factor: "SoA"},
    { id: 22, question: "My child's heart beats very fast for no reason.", factor: "PD"},
    { id: 23, question: "My child feel shaky for no reason.", factor: "PD"},
    { id: 24, question: "My child feels restless.", factor: "MDD"},
    { id: 25, question: "My child gets nervous when he/she have to talk in front of his/her classmates.", factor: "SoA"},
    { id: 26, question: "My child worries that something bad will happen to him/her.", factor: "GAD"},
    { id: 27, question: "My child doesn't want to hang out with his/her friends.", factor: "MDD"},
    { id: 28, question: "My child can't get rid of bad thoughts in his/her head.", factor: "OCD",},
    { id: 29, question: "My child doesn't feel like going to school.", factor:"SoA"},
    { id: 30, question: "My child feels hopeless.", factor: "MDD"},
    { id: 31, question: "My child has to repeat doing things over and over(like washing hands)", factor: "OCD"},
    { id: 32, question: "My child has thoughts of harming his/herself.", factor: "MDD"},
    { id: 33, question: "My child feels like a failure.", factor: "SoA"},
    { id: 34, question: "My child worries about what people think of him/her.", factor: "SoA"},
    { id: 35, question: "My child suddenly feels scared for no reason.", factor: "PD"},
    { id: 36, question: "My child worries when he/she goes to bed at night.", factor: "SeA"},
    { id: 37, question: "My child keeps checking that he/she has done things right (like checking the door).", factor: "OCD"},
    { id: 38, question: "My child worries that bad things will happen to me.", factor: "GAD"},
    { id: 39, question: "My child gets angry easily.", factor: "MDD"},
    { id: 40, question: "My child has bad or weird images in his/her mind.", factor: "OCD"},
    { id: 41, question: "My child is scared of being in crowded places.", factor: "PD"},
    { id: 42, question: "My child's heart beats fast when he/she has a problem.", factor: "PD"},
    { id: 43, question: "My child suddenly starts trembling for no reason.", factor: "PD"},
    { id: 44, question: "My child has to think of certain thoughts (like numbers or words) to stop bad things from happening.", factor: "OCD"},
    { id: 45, question: "My child has problems with his/her appetite (eating too little or too much).", factor: "MDD"},
    { id: 46, question: "All of a sudden, my child feels dizzy or faint for no reason.", factor: "PD"},
    { id: 47, question: "My child worries that he/she would make a fool of him/herself.", factor: "SoA"},
    { id: 48, question: "Suddenly, my child feels like catching his/her breath.", factor: "PD"},
    { id: 49, question: "My child feels that people don't like him/her.", factor: "SoA"},
    { id: 50, question: "My child just wants to be alone.", factor: "MDD"},
  ];
  
  export default ParentQuestions;