import { Question } from '@/types/adapts';

const ParentQuestions: Question[] = [
  { id: 1, question: "I often feel sad or emotionally drained as a parent.", factor: "MDD" },
  { id: 2, question: "I feel anxious when I am away from my child.", factor: "SeA" },
  { id: 3, question: "I find myself worrying about many things in my life.", factor: "GAD" },
  { id: 4, question: "I worry excessively when I am separated from my child.", factor: "SeA" },
  { id: 5, question: "I have trouble sleeping because of stress or worries.", factor: "MDD" },
  { id: 6, question: "I often feel like I don’t have the energy to handle daily responsibilities.", factor: "MDD" },
  { id: 7, question: "Sometimes I suddenly feel scared or anxious for no clear reason.", factor: "PD" },
  { id: 8, question: "When I am stressed or worried, I feel it physically (like stomach discomfort).", factor: "PD" },
  { id: 9, question: "I worry a lot about making mistakes as a parent.", factor: "SoA" },
  { id: 10, question: "I often feel physically and emotionally exhausted.", factor: "MDD" },
  { id: 11, question: "I no longer find enjoyment in activities I used to like.", factor: "MDD" },
  { id: 12, question: "I have difficulty concentrating on tasks.", factor: "MDD" },
  { id: 13, question: "I feel nervous or anxious when I feel judged by others.", factor: "SoA" },
  { id: 14, question: "Thoughts about death or losing loved ones sometimes bother me.", factor: "GAD" },
  { id: 15, question: "I frequently worry that something bad might happen.", factor: "GAD" },
  { id: 16, question: "I worry about whether I am doing well enough as a parent.", factor: "SoA" },
  { id: 17, question: "It bothers me deeply when people are upset or disappointed with me.", factor: "SoA" },
  { id: 18, question: "Sometimes I feel unmotivated to do anything.", factor: "MDD" },
  { id: 19, question: "I worry that something bad might happen to my child or loved ones.", factor: "GAD" },
  { id: 20, question: "I feel uneasy when I am not close to my child.", factor: "SeA" },
  { id: 21, question: "I worry about embarrassing myself in front of others.", factor: "SoA" },
  { id: 22, question: "My heart sometimes races suddenly even when I’m not physically active.", factor: "PD" },
  { id: 23, question: "I sometimes feel shaky or tense without a clear reason.", factor: "PD" },
  { id: 24, question: "I often feel restless or unable to relax.", factor: "MDD" },
  { id: 25, question: "I get nervous when I have to speak or interact in front of others.", factor: "SoA" },
  { id: 26, question: "I worry that something bad might happen to me.", factor: "GAD" },
  { id: 27, question: "I sometimes withdraw from social interactions.", factor: "MDD" },
  { id: 28, question: "I struggle with intrusive thoughts that I cannot easily dismiss.", factor: "OCD" },
  { id: 29, question: "I sometimes avoid situations that make me uncomfortable socially.", factor: "SoA" },
  { id: 30, question: "I sometimes feel hopeless about the future.", factor: "MDD" },
  { id: 31, question: "I feel the need to repeat certain actions (like checking things multiple times).", factor: "OCD" },
  { id: 32, question: "I sometimes have thoughts about harming myself.", factor: "MDD" },
  { id: 33, question: "I sometimes feel like I am failing as a parent or person.", factor: "SoA" },
  { id: 34, question: "I worry a lot about what other people think of me.", factor: "SoA" },
  { id: 35, question: "I sometimes feel sudden waves of fear or panic.", factor: "PD" },
  { id: 36, question: "I worry excessively when my child is out of my sight.", factor: "SeA" },
  { id: 37, question: "I repeatedly check things to make sure they are correct or safe.", factor: "OCD" },
  { id: 38, question: "I worry that bad things might happen to my family.", factor: "GAD" },
  { id: 39, question: "I find myself getting irritated or angry easily.", factor: "MDD" },
  { id: 40, question: "I sometimes have disturbing or unwanted thoughts that come into my mind.", factor: "OCD" },
  { id: 41, question: "I feel uncomfortable in crowded places.", factor: "PD" },
  { id: 42, question: "My heart beats fast when I feel overwhelmed.", factor: "PD" },
  { id: 43, question: "I sometimes start trembling when I feel anxious.", factor: "PD" },
  { id: 44, question: "I feel like I must think or do certain things to prevent something bad from happening.", factor: "OCD" },
  { id: 45, question: "My appetite changes when I feel stressed or emotionally low.", factor: "MDD" },
  { id: 46, question: "I sometimes feel dizzy or faint when I become anxious.", factor: "PD" },
  { id: 47, question: "I worry that I might embarrass myself in front of others.", factor: "SoA" },
  { id: 48, question: "Sometimes I suddenly feel like I cannot catch my breath.", factor: "PD" },
  { id: 49, question: "I sometimes feel that others do not like me.", factor: "SoA" },
  { id: 50, question: "I sometimes just want to be alone and avoid everyone.", factor: "MDD" }
];

// Child focused
// const ParentQuestions: Question[] = [
//     { id: 1,  question: "My child feels sad.", factor: "MDD" },
//     { id: 2,  question: "My child feels afraid of being alone at home.", factor: "SeA" },
//     { id: 3,  question: "My child worries about stuff.", factor: "GAD" },
//     { id: 4,  question: "My child worries when I'm away from him/her.", factor: "SeA" },
//     { id: 5,  question: "My child has problems sleeping.", factor: "MDD" },
//     { id: 6,  question: "My child has no energy to do things.", factor: "MDD" },
//     { id: 7,  question: "My child feels afraid for no reason.", factor: "PD"},
//     { id: 8,  question: "When my child has a problem, his/her stomach gets upset.", factor: "PD"},
//     { id: 9,  question: "My child worries about making mistakes.", factor: "SoA"},
//     { id: 10, question: "My child gets very tired.", factor: "MDD"},
//     { id: 11, question: "My child doesn't have much fun anymore.",  factor: "MDD"},
//     { id: 12, question: "My child has problems concentrating.", factor: "MDD"},
//     { id: 13, question: "My child gets scared when he/she has to take a test.", factor: "SoA"},
//     { id: 14, question: "My child is bothered by thoughts of dying.", factor: "GAD"},
//     { id: 15, question: "My child worries that something bad will happen.", factor: "GAD"},
//     { id: 16, question: "My child worries about getting bad grades.", factor: "SoA"},
//     { id: 17, question: "It bothers my child when someone is angry with him/her.", factor: "SoA"},
//     { id: 18, question: "My child doesn't feel like doing anything.", factor: "MDD"},
//     { id: 19, question: "My child worries that something bad will happen to me or people he/she loves.", factor: "GAD"},
//     { id: 20, question: "My child is scared of sleeping alone.", factor: "SeA"},
//     { id: 21, question: "My child worries about embarrassing him/her self.", factor: "SoA"},
//     { id: 22, question: "My child's heart beats very fast for no reason.", factor: "PD"},
//     { id: 23, question: "My child feel shaky for no reason.", factor: "PD"},
//     { id: 24, question: "My child feels restless.", factor: "MDD"},
//     { id: 25, question: "My child gets nervous when he/she have to talk in front of his/her classmates.", factor: "SoA"},
//     { id: 26, question: "My child worries that something bad will happen to him/her.", factor: "GAD"},
//     { id: 27, question: "My child doesn't want to hang out with his/her friends.", factor: "MDD"},
//     { id: 28, question: "My child can't get rid of bad thoughts in his/her head.", factor: "OCD",},
//     { id: 29, question: "My child doesn't feel like going to school.", factor:"SoA"},
//     { id: 30, question: "My child feels hopeless.", factor: "MDD"},
//     { id: 31, question: "My child has to repeat doing things over and over(like washing hands)", factor: "OCD"},
//     { id: 32, question: "My child has thoughts of harming his/herself.", factor: "MDD"},
//     { id: 33, question: "My child feels like a failure.", factor: "SoA"},
//     { id: 34, question: "My child worries about what people think of him/her.", factor: "SoA"},
//     { id: 35, question: "My child suddenly feels scared for no reason.", factor: "PD"},
//     { id: 36, question: "My child worries when he/she goes to bed at night.", factor: "SeA"},
//     { id: 37, question: "My child keeps checking that he/she has done things right (like checking the door).", factor: "OCD"},
//     { id: 38, question: "My child worries that bad things will happen to me.", factor: "GAD"},
//     { id: 39, question: "My child gets angry easily.", factor: "MDD"},
//     { id: 40, question: "My child has bad or weird images in his/her mind.", factor: "OCD"},
//     { id: 41, question: "My child is scared of being in crowded places.", factor: "PD"},
//     { id: 42, question: "My child's heart beats fast when he/she has a problem.", factor: "PD"},
//     { id: 43, question: "My child suddenly starts trembling for no reason.", factor: "PD"},
//     { id: 44, question: "My child has to think of certain thoughts (like numbers or words) to stop bad things from happening.", factor: "OCD"},
//     { id: 45, question: "My child has problems with his/her appetite (eating too little or too much).", factor: "MDD"},
//     { id: 46, question: "All of a sudden, my child feels dizzy or faint for no reason.", factor: "PD"},
//     { id: 47, question: "My child worries that he/she would make a fool of him/herself.", factor: "SoA"},
//     { id: 48, question: "Suddenly, my child feels like catching his/her breath.", factor: "PD"},
//     { id: 49, question: "My child feels that people don't like him/her.", factor: "SoA"},
//     { id: 50, question: "My child just wants to be alone.", factor: "MDD"},
//   ];
  
  export default ParentQuestions;