import { Question } from '@/types/adapts';

const StudentQuestions: Question[] = [
  { id: 1, question: "I feel sad.", factor: "MDD" },
  { id: 2, question: "I feel afraid of being alone at home.", factor: "SeA" }, 
  { id: 3, question: "I worry about stuff.", factor: "GAD" },
  { id: 4, question: "I get worried when I am away from my family.", factor: "SeA" }, 
  { id: 5, question: "I have problems sleeping.", factor: "MDD" },
  { id: 6, question: "I have no energy to do things.", factor: "MDD" },
  { id: 7, question: "I feel afraid for no reason.", factor: "PD"},
  { id: 8, question: "When I have a problem, my stomach gets upset.", factor: "PD"},
  { id: 9, question: "I worry about making mistakes.", factor: "SoA"},
  { id: 10, question: "I am very tired.", factor: "MDD"},
  { id: 11, question: "I dont have much fun anymore.",  factor: "MDD"},
  { id: 12, question: "I have problems concentrating.", factor: "MDD"},
  { id: 13, question: "I feel scared when I have to take a test.", factor: "SoA"},
  { id: 14, question: "I am bothered by thought of dying.", factor: "GAD"},
  { id: 15, question: "I worry that something bad will happen.", factor: "GAD"},
  { id: 16, question: "I worry about getting bad grades.", factor: "SoA"},
  { id: 17, question: "It bothers me when someone is angry with me.", factor: "SoA"},
  { id: 18, question: "I dont feel like doing anything.", factor: "MDD"},
  { id: 19, question: "I worry that something bad will happen to my parents.", factor: "GAD"},
  { id: 20, question: "I am scared of sleeping alone.", factor: "SeA"},
  { id: 21, question: "I worry about embarrassing myself.", factor: "SoA"},
  { id: 22, question: "My heart beats very fast for no reason.", factor: "PD"},
  { id: 23, question: "I feel shaky for no reason.", factor: "PD"},
  { id: 24, question: "I feel restless.", factor: "MDD"},
  { id: 25, question: "I get nervous when I have to talk in front of my classmates.", factor: "SoA"},
  { id: 26, question: "I worry that something bad will happen to me.", factor: "GAD"},
  { id: 27, question: "I dont want to hang out with my friends.", factor: "MDD"},
  { id: 28, question: "I cant get rid of bad thoughts in my head.", factor: "OCD",},
  { id: 29, question: "I dont feel like going to school.", factor:"SoA"},
  { id: 30, question: "I feel hopeless.", factor: "MDD"},
  { id: 31, question: "I have to repeat doing things over and over.", factor: "OCD"},
  { id: 32, question: "I have thoughts of harming myself.", factor: "MDD"},
  { id: 33, question: "I feel like a failure.", factor: "SoA"},
  { id: 34, question: "I worry about what people think of me.", factor: "SoA"},
  { id: 35, question: "I suddenly feel scared for no reason.", factor: "PD"},
  { id: 36, question: "I worry when I go to bed at night.", factor: "SeA"},
  { id: 37, question: "I keep checking that I have done things right (like checking the door).", factor: "OCD"},
  { id: 38, question: "I worry that bad things will happen to me.", factor: "GAD"},
  { id: 39, question: "I get angry easily.", factor: "MDD"},
  { id: 40, question: "I have bad or weird images in my mind.", factor: "OCD"},
  { id: 41, question: "I am scared of being in crowded places.", factor: "PD"},
  { id: 42, question: "My heart beats fast when I have a problem.", factor: "PD"},
  { id: 43, question: "I suddenly start trembling for no reason.", factor: "PD"},
  { id: 44, question: "I have to think of certain thoughts (like numbers or words) to stop bad things.", factor: "OCD"},
  { id: 45, question: "I have problems with my appetite (eating too little or too much).", factor: "MDD"},
  { id: 46, question: "All of a sudden, I feel dizzy or faint for no reason.", factor: "PD"},
  { id: 47, question: "I worry that I would/will make a fool of myself.", factor: "SoA"},
  { id: 48, question: "Suddenly, I feel like catching my breath.", factor: "PD"},
  { id: 49, question: "I feel that people dont like me.", factor: "SoA"},
  { id: 50, question: "I just want to be alone.", factor: "MDD"},
];

export default StudentQuestions;