import { Question } from '@/types/adapts';

const TeacherQuestions: Question[] = [
  { id: 1, question: "I often feel sad or emotionally low.", factor: "MDD" },
  { id: 2, question: "I feel uneasy when I have to be alone or without support.", factor: "SeA" },
  { id: 3, question: "I find myself worrying about many things throughout the day.", factor: "GAD" },
  { id: 4, question: "I feel anxious when I am separated from people I rely on emotionally.", factor: "SeA" },
  { id: 5, question: "I have trouble sleeping or resting well.", factor: "MDD" },
  { id: 6, question: "I often feel like I do not have enough energy for my daily responsibilities.", factor: "MDD" },
  { id: 7, question: "I sometimes feel suddenly scared or anxious for no clear reason.", factor: "PD" },
  { id: 8, question: "When I am stressed, I feel it physically, such as through stomach discomfort.", factor: "PD" },
  { id: 9, question: "I worry a lot about making mistakes in my work.", factor: "SoA" },
  { id: 10, question: "I often feel very tired or emotionally drained.", factor: "MDD" },
  { id: 11, question: "I no longer enjoy some things I used to enjoy.", factor: "MDD" },
  { id: 12, question: "I have difficulty concentrating on tasks.", factor: "MDD" },
  { id: 13, question: "I feel very anxious in evaluative situations or when I feel judged.", factor: "SoA" },
  { id: 14, question: "Thoughts about death or losing people sometimes bother me.", factor: "GAD" },
  { id: 15, question: "I often worry that something bad might happen.", factor: "GAD" },
  { id: 16, question: "I worry that I am not doing well enough in my role.", factor: "SoA" },
  { id: 17, question: "I get deeply affected when someone seems upset or disappointed with me.", factor: "SoA" },
  { id: 18, question: "I often struggle to feel motivated to start or finish tasks.", factor: "MDD" },
  { id: 19, question: "I worry that something bad might happen to my loved ones.", factor: "GAD" },
  { id: 20, question: "I feel uncomfortable when I am away from people who make me feel safe.", factor: "SeA" },
  { id: 21, question: "I worry about embarrassing myself in front of others.", factor: "SoA" },
  { id: 22, question: "My heart sometimes races even when there is no clear physical reason.", factor: "PD" },
  { id: 23, question: "I sometimes feel shaky or tense without a clear cause.", factor: "PD" },
  { id: 24, question: "I often feel restless or unable to relax.", factor: "MDD" },
  { id: 25, question: "I get nervous when I have to speak or perform in front of others.", factor: "SoA" },
  { id: 26, question: "I worry that something bad might happen to me.", factor: "GAD" },
  { id: 27, question: "I tend to withdraw from others when I am feeling low.", factor: "MDD" },
  { id: 28, question: "I experience intrusive thoughts that are hard to dismiss.", factor: "OCD" },
  { id: 29, question: "I sometimes avoid situations that make me socially uncomfortable.", factor: "SoA" },
  { id: 30, question: "I sometimes feel hopeless about the future.", factor: "MDD" },
  { id: 31, question: "I feel the need to repeat certain actions more than necessary.", factor: "OCD" },
  { id: 32, question: "I sometimes have thoughts of harming myself.", factor: "MDD" },
  { id: 33, question: "I sometimes feel like a failure or not good enough.", factor: "SoA" },
  { id: 34, question: "I worry a lot about what other people think of me.", factor: "SoA" },
  { id: 35, question: "I sometimes experience sudden episodes of intense fear.", factor: "PD" },
  { id: 36, question: "I worry when I am apart from people I care deeply about.", factor: "SeA" },
  { id: 37, question: "I repeatedly check things to make sure they are correct or safe.", factor: "OCD" },
  { id: 38, question: "I worry that something bad might happen to my family or loved ones.", factor: "GAD" },
  { id: 39, question: "I get irritated or angry more easily than usual.", factor: "MDD" },
  { id: 40, question: "I sometimes experience disturbing thoughts or mental images.", factor: "OCD" },
  { id: 41, question: "I feel uncomfortable in crowded places.", factor: "PD" },
  { id: 42, question: "When I feel overwhelmed, my heart starts beating fast.", factor: "PD" },
  { id: 43, question: "I sometimes start trembling when I feel anxious.", factor: "PD" },
  { id: 44, question: "I feel like I need to think or do certain things to prevent something bad from happening.", factor: "OCD" },
  { id: 45, question: "My appetite changes when I feel stressed or emotionally low.", factor: "MDD" },
  { id: 46, question: "I sometimes feel dizzy or faint when I become anxious.", factor: "PD" },
  { id: 47, question: "I worry that I might make a fool of myself in front of others.", factor: "SoA" },
  { id: 48, question: "I sometimes suddenly feel short of breath or unable to catch my breath.", factor: "PD" },
  { id: 49, question: "I sometimes feel that other people do not like me.", factor: "SoA" },
  { id: 50, question: "I sometimes prefer to isolate myself from others.", factor: "MDD" },
];

// Student focused
// const TeacherQuestions: Question[] = [
//   { id: 1,  question: "This student often appears sad or down at school (e.g., tearful, flat mood).", factor: "MDD" },
//   { id: 2,  question: "This student is afraid to be alone at school (e.g., reluctant to go to the restroom or stay in a room without an adult).", factor: "SeA" },
//   { id: 3,  question: "This student frequently seems worried at school.", factor: "GAD" },
//   { id: 4,  question: "This student worries when separated from caregivers (e.g., at drop‑off or if unable to contact home).", factor: "SeA" },
//   { id: 5,  question: "This student appears tired or sleepy at school or reports difficulty sleeping.", factor: "MDD" },
//   { id: 6,  question: "This student often shows low energy in class (slow to start tasks, low participation).", factor: "MDD" },
//   { id: 7,  question: "This student suddenly appears fearful or panicky at school without a clear reason.", factor: "PD" },
//   { id: 8,  question: "When facing a problem at school, this student complains of stomachaches or nausea.", factor: "PD" },
//   { id: 9,  question: "This student is overly worried about making mistakes or not being perfect on schoolwork.", factor: "SoA" },
//   { id: 10, question: "This student often seems very tired or fatigued at school.", factor: "MDD" },
//   { id: 11, question: "This student shows little enjoyment in activities they used to like at school.", factor: "MDD" },
//   { id: 12, question: "This student has difficulty concentrating during class activities.", factor: "MDD" },
//   { id: 13, question: "This student appears very anxious during tests.", factor: "SoA" },
//   { id: 14, question: "This student seems preoccupied with death (talks/writes/draws about death more than expected).", factor: "GAD" },
//   { id: 15, question: "This student often expresses that something bad might happen.", factor: "GAD" },
//   { id: 16, question: "This student worries excessively about getting bad grades.", factor: "SoA" },
//   { id: 17, question: "This student becomes very upset when someone seems angry with them (teacher or peer).", factor: "SoA" },
//   { id: 18, question: "This student often lacks motivation to start or complete tasks.", factor: "MDD" },
//   { id: 19, question: "This student worries that something bad will happen to family/caregivers during the school day.", factor: "GAD" },
//   { id: 20, question: "This student is afraid to be alone during rest/quiet times or when away from familiar adults at school.", factor: "SeA" },
//   { id: 21, question: "This student worries about being embarrassed in front of classmates.", factor: "SoA" },
//   { id: 22, question: "At school, this student reports or shows signs of a racing heartbeat without a clear cause.", factor: "PD" },
//   { id: 23, question: "This student suddenly appears shaky or reports feeling shaky without a clear cause.", factor: "PD" },
//   { id: 24, question: "This student appears restless or on edge in class.", factor: "MDD" },
//   { id: 25, question: "This student becomes very nervous when asked to speak or present in front of the class.", factor: "SoA" },
//   { id: 26, question: "This student worries that something bad will happen to them at school.", factor: "GAD" },
//   { id: 27, question: "This student withdraws from peers or avoids joining friends during class, lunch, or recess.", factor: "MDD" },
//   { id: 28, question: "This student reports or seems preoccupied with intrusive 'bad' thoughts that are hard to dismiss.", factor: "OCD" },
//   { id: 29, question: "This student frequently asks to go home or expresses not wanting to be at school.", factor: "SoA" },
//   { id: 30, question: "This student makes statements or shows signs of hopelessness (e.g., 'what's the point?').", factor: "MDD" },
//   { id: 31, question: "This student repeats certain actions or rituals (e.g., washing, erasing, redoing work) more than needed.", factor: "OCD" },
//   { id: 32, question: "This student expresses thoughts of self-harm.", factor: "MDD" },
//   { id: 33, question: "This student expresses feeling like a failure or not good enough.", factor: "SoA" },
//   { id: 34, question: "This student appears overly concerned about what others think of them.", factor: "SoA" },
//   { id: 35, question: "This student has sudden episodes of intense fear without an obvious trigger at school.", factor: "PD" },
//   { id: 36, question: "This student reports worrying at night (shares this with the teacher or counselor).", factor: "SeA" },
//   { id: 37, question: "This student repeatedly checks that things are 'just right' or that work is done correctly (e.g., rechecking many times).", factor: "OCD" },
//   { id: 38, question: "This student worries that something bad will happen to their caregiver/family while they are at school.", factor: "GAD" },
//   { id: 39, question: "This student gets irritable or angry easily at school.", factor: "MDD" },
//   { id: 40, question: "This student mentions disturbing or intrusive images or thoughts.", factor: "OCD" },
//   { id: 41, question: "This student is fearful of crowded school spaces (hallways, assemblies, cafeteria) and may avoid them.", factor: "PD" },
//   { id: 42, question: "When stressed at school, this student appears to have a fast heartbeat or says their heart is racing.", factor: "PD" },
//   { id: 43, question: "This student suddenly starts trembling without a clear cause at school.", factor: "PD" },
//   { id: 44, question: "This student seems to engage in mental rituals (e.g., silently repeating words/numbers) to prevent something bad from happening.", factor: "OCD" },
//   { id: 45, question: "During school meals/snacks, this student shows changes in appetite (eats very little or much more than usual).", factor: "MDD" },
//   { id: 46, question: "This student suddenly appears dizzy or lightheaded without a clear cause at school.", factor: "PD" },
//   { id: 47, question: "This student worries about making a fool of themselves in front of others at school.", factor: "SoA" },
//   { id: 48, question: "This student suddenly seems short of breath or struggles to catch their breath without a clear cause.", factor: "PD" },
//   { id: 49, question: "This student says or acts as if peers don't like them.", factor: "SoA" },
//   { id: 50, question: "This student prefers to be alone or isolates during school activities.", factor: "MDD" },
// ];

export default TeacherQuestions;
