import { Question } from '@/types/adapts';

const TeacherQuestions: Question[] = [
  { id: 1,  question: "This student often appears sad or down at school (e.g., tearful, flat mood).", factor: "MDD" },
  { id: 2,  question: "This student is afraid to be alone at school (e.g., reluctant to go to the restroom or stay in a room without an adult).", factor: "SeA" },
  { id: 3,  question: "This student frequently seems worried at school.", factor: "GAD" },
  { id: 4,  question: "This student worries when separated from caregivers (e.g., at drop‑off or if unable to contact home).", factor: "SeA" },
  { id: 5,  question: "This student appears tired or sleepy at school or reports difficulty sleeping.", factor: "MDD" },
  { id: 6,  question: "This student often shows low energy in class (slow to start tasks, low participation).", factor: "MDD" },
  { id: 7,  question: "This student suddenly appears fearful or panicky at school without a clear reason.", factor: "PD" },
  { id: 8,  question: "When facing a problem at school, this student complains of stomachaches or nausea.", factor: "PD" },
  { id: 9,  question: "This student is overly worried about making mistakes or not being perfect on schoolwork.", factor: "SoA" },
  { id: 10, question: "This student often seems very tired or fatigued at school.", factor: "MDD" },
  // { id: 11, question: "This student shows little enjoyment in activities they used to like at school.", factor: "MDD" },
  // { id: 12, question: "This student has difficulty concentrating during class activities.", factor: "MDD" },
  // { id: 13, question: "This student appears very anxious during tests.", factor: "SoA" },
  // { id: 14, question: "This student seems preoccupied with death (talks/writes/draws about death more than expected).", factor: "GAD" },
  // { id: 15, question: "This student often expresses that something bad might happen.", factor: "GAD" },
  // { id: 16, question: "This student worries excessively about getting bad grades.", factor: "SoA" },
  // { id: 17, question: "This student becomes very upset when someone seems angry with them (teacher or peer).", factor: "SoA" },
  // { id: 18, question: "This student often lacks motivation to start or complete tasks.", factor: "MDD" },
  // { id: 19, question: "This student worries that something bad will happen to family/caregivers during the school day.", factor: "GAD" },
  // { id: 20, question: "This student is afraid to be alone during rest/quiet times or when away from familiar adults at school.", factor: "SeA" },
  // { id: 21, question: "This student worries about being embarrassed in front of classmates.", factor: "SoA" },
  // { id: 22, question: "At school, this student reports or shows signs of a racing heartbeat without a clear cause.", factor: "PD" },
  // { id: 23, question: "This student suddenly appears shaky or reports feeling shaky without a clear cause.", factor: "PD" },
  // { id: 24, question: "This student appears restless or on edge in class.", factor: "MDD" },
  // { id: 25, question: "This student becomes very nervous when asked to speak or present in front of the class.", factor: "SoA" },
  // { id: 26, question: "This student worries that something bad will happen to them at school.", factor: "GAD" },
  // { id: 27, question: "This student withdraws from peers or avoids joining friends during class, lunch, or recess.", factor: "MDD" },
  // { id: 28, question: "This student reports or seems preoccupied with intrusive 'bad' thoughts that are hard to dismiss.", factor: "OCD" },
  // { id: 29, question: "This student frequently asks to go home or expresses not wanting to be at school.", factor: "SoA" },
  // { id: 30, question: "This student makes statements or shows signs of hopelessness (e.g., 'what's the point?').", factor: "MDD" },
  // { id: 31, question: "This student repeats certain actions or rituals (e.g., washing, erasing, redoing work) more than needed.", factor: "OCD" },
  // { id: 32, question: "This student expresses thoughts of self-harm.", factor: "MDD" },
  // { id: 33, question: "This student expresses feeling like a failure or not good enough.", factor: "SoA" },
  // { id: 34, question: "This student appears overly concerned about what others think of them.", factor: "SoA" },
  // { id: 35, question: "This student has sudden episodes of intense fear without an obvious trigger at school.", factor: "PD" },
  // { id: 36, question: "This student reports worrying at night (shares this with the teacher or counselor).", factor: "SeA" },
  // { id: 37, question: "This student repeatedly checks that things are 'just right' or that work is done correctly (e.g., rechecking many times).", factor: "OCD" },
  // { id: 38, question: "This student worries that something bad will happen to their caregiver/family while they are at school.", factor: "GAD" },
  // { id: 39, question: "This student gets irritable or angry easily at school.", factor: "MDD" },
  // { id: 40, question: "This student mentions disturbing or intrusive images or thoughts.", factor: "OCD" },
  // { id: 41, question: "This student is fearful of crowded school spaces (hallways, assemblies, cafeteria) and may avoid them.", factor: "PD" },
  // { id: 42, question: "When stressed at school, this student appears to have a fast heartbeat or says their heart is racing.", factor: "PD" },
  // { id: 43, question: "This student suddenly starts trembling without a clear cause at school.", factor: "PD" },
  // { id: 44, question: "This student seems to engage in mental rituals (e.g., silently repeating words/numbers) to prevent something bad from happening.", factor: "OCD" },
  // { id: 45, question: "During school meals/snacks, this student shows changes in appetite (eats very little or much more than usual).", factor: "MDD" },
  // { id: 46, question: "This student suddenly appears dizzy or lightheaded without a clear cause at school.", factor: "PD" },
  // { id: 47, question: "This student worries about making a fool of themselves in front of others at school.", factor: "SoA" },
  // { id: 48, question: "This student suddenly seems short of breath or struggles to catch their breath without a clear cause.", factor: "PD" },
  // { id: 49, question: "This student says or acts as if peers don't like them.", factor: "SoA" },
  // { id: 50, question: "This student prefers to be alone or isolates during school activities.", factor: "MDD" },
];

export default TeacherQuestions;
